services:
  backend:
    build: ./backend
    container_name: ajaj_backend
    ports:
      - "5000:5000"
    volumes:
      # ZMIANA: Mapujemy Twój lokalny folder 'database' do '/app/database' w kontenerze
      - ./database:/app/database
      - ./backend:/app
    environment:
      - FLASK_APP=init.py
      - FLASK_DEBUG=1
      # ZMIANA: Baza danych ląduje bezpośrednio w zmapowanym folderze
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/database/transcriptions.db
      # ZMIANA: Pliki użytkowników trafiają do podfolderu Users w bazie
      - UPLOAD_FOLDER=/app/database/Users
      - TEXT_TRANSFORM_URL=http://text_transform:5001
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - text_transform

  text_transform:
    build: ./textTransform
    container_name: ajaj_transform
    ports:
      - "5001:5001"
    volumes:
      # ZMIANA: To samo mapowanie co w backendzie
      - ./database:/app/database
      - ./textTransform:/app
    environment:
      # ZMIANA: Wskazujemy na ten sam folder Users co backend
      - DATA_DIR=/app/database/Users
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend:
    build: ./frontend
    container_name: ajaj_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
