###  SIGNUP

POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "name": "Test2",
  "email": "test2@example.com",
  "password": "password123"
}

###  LOGIN

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "password123"
}

### GET CURRENT USER (/me)

GET http://localhost:5000/auth/me

###  UPDATE CURRENT USER

PUT http://localhost:5000/auth/me
Content-Type: application/json

{
  "name": "Updated Test User"
}

###  LOGOUT

POST http://localhost:5000/auth/logout

###  ADMIN LOGIN (hardcoded admin)

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "admin@system.com",
  "password": "admin123"
}

###  ADMIN GET ALL USERS

GET http://localhost:5000/auth/users


###  ADMIN GET USER BY ID

GET http://localhost:5000/auth/users/1

###  ADMIN UPDATE USER

PUT http://localhost:5000/auth/users/1
Content-Type: application/json

{
  "name": "AdminRenamed"
}

###  ADMIN DELETE USER

DELETE http://localhost:5000/auth/users/1

